// <auto-generated />
namespace BIGSCHOOL_LEVANTHANG.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class INIT_PROJECT : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(INIT_PROJECT));
        
        string IMigrationMetadata.Id
        {
            get { return "202206030118559_INIT_PROJECT"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
